---
name: terrarium - terraform tools for dev environment

on:
  push:
    branches:
      - master
  #pull_request:

env:
  # github.repository as <account>/<repo>
  IMAGE_BASE: ${{ github.repository }}

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["terrarium"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=false" \
            --file ./terraform/docker/Dockerfile ./terraform/docker
      -
        name: Docker Buildx (push)
        if: success() && github.event_name != 'pull_request'
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      #-
      #  name: Build and push image
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./terraform/docker
      #    push: true
      #    file: terraform/docker/Dockerfile.${{ matrix.image }}
      #    tags: |
      #      ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
