---
name: terraform image

on:
  push:
    branches:
      - master
  pull_request:

env:
  # github.repository as <account>/<repo>
  IMAGE_BASE: ${{ github.repository }}

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["rocky8"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: terraform/docker/Dockerfile.${{ matrix.image }}
          tags: localhost:5000/ods-contrib-terraform-${{ matrix.image }}:latest
          outputs: type=docker,dest=/tmp/image-ods-contrib-terraform-${{ matrix.image }}.tar
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildx-image-ods-contrib-terraform-${{ matrix.image }}
          path: /tmp/image-ods-contrib-terraform-${{ matrix.image }}.tar
          retention-days: 1
      -
        name: Push image to ghcr.io
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          image=${{ matrix.image }}
          echo "Push ods-contrib-terraform-$image to ghcr.io"
          docker tag localhost:5000/ods-contrib-terraform-$image:latest ghcr.io/nichtraunzer/${{ env.IMAGE_BASE }}/ods-contrib-terraform-$image:latest
          docker push ghcr.io/nichtraunzer/${{  env.IMAGE_BASE }}/ods-contrib-terraform-$image:latest
